### ISSUE TITLE
Move kube-inject to apiserver

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#14]
@kyessenov commented on [Thu Apr 27 2017](https://github.com/istio/pilot/issues/606)

Since we are removing dependencies on k8s in `istioctl`, the remaining piece is moving `kube-inject` to an in-cluster service. I think we need to define an HTTP endpoint on `apiserver` that fulfills the proposed k8s web-hook admission controller and can be used by `istioctl`, thus removing any need for k8s auth in istioctl.

@andraxylia @ayj

**Comment by ayj** [comment]
@kyessenov @andraxylia, in which repo will the k8s initializer/admission controller for transparent proxy injection reside?

**Comment by andraxylia** [comment]
There is no benefit in moving kube-inject to server side and re-writing kube-inject, exposing a web servcie for it, etc. kube-inject only modifies the yaml files, so it can very well stay on the client side.
We do however need to restore it to a working state, it is broken now, since k8s cluster < 1.7 will still need to use it.

If istioctl is decoupled from kubernetes, we can maybe have kube-inject as a separate command, that we can deprecate once all kubernetes clusters migrate to 1.7+. This way we only need to write a cobra file for kube-inject.

kubectl apply -f < kube-inject myapp.yaml

**Comment by ldemailly** [comment]
I think kube-inject works on master while it's getting replaced anyway soon
